name: Flutter Lint

on:
  pull_request:
    branches: [development]

jobs:
  lint:
    name: Dart Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze
